language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm dist
cache:
  directories:
    - node_modules
notifications:
  email:       false
